name: RankMine Health Check
on:
  schedule:
    - cron: '0 2 * * *'   # 2 AM daily (IST)
  workflow_dispatch:      # manual trigger
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install axios
      - run: node health.js
